@port=3001
@api=http://localhost:{{port}}/api/users
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDBjMDcyZmM0ZTY0OTk4NDgxYTllOCIsInJvbGUiOiJjb250cmlidXRvciIsInVzZXJuYW1lIjoiUHVua0hhemFyZDA5NSIsImlhdCI6MTcyNjg5NTk3MCwiZXhwIjoxNzI2OTEwMzcwfQ.TQDXmLFVbBQdj7GahzTByVoyOnOOyuZy4Llo4rQ6CSs
@reset_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlrdGlzYWQucmFzaGlkQGdtYWlsLmNvbSIsImlhdCI6MTcyMzcwNzE1MiwiZXhwIjoxNzIzNzkzNTUyfQ.D8DhaqhP1Eg26l6f43lt0gQun_2nW6b_tdLbMw32D-A

@test_email="iktisad.rashid@gmail.com"
@test_password="securepassword123"
@test_username="PunkHazard095"


###--------Check If User Exists-------###
### EMAIL
###----->
GET {{api}}/check-exists?email=iktisad.rashid@gmail.com
### USERNAME
###----->
GET {{api}}/check-exists?username=PunkHazard095

###-----------------------------------###


###-------------Login User------------###
###----->
POST {{api}}/login
Content-Type: application/json

{
    "email":"iktisad.rashid@gmail.com",
    "password": "securepassword123"
}

###-----------------------------------###


###------------Create User------------###
###----->
POST {{api}}/signup
Content-Type: application/json

{
  "username": "PunkHazard095",
  "email": "iktisad.rashid@gmail.com",
  "password": "securepassword123",
  "dob": "1995-10-30",
  "profile": {
    "firstName": "Iktisad",
    "lastName": "Rashid"
  }
}

###-----------------------------------###


###-------------Update User------------###
###----->
PATCH {{api}}/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
// "email": "ine.newemail@example.com",
  "profile": {
    "bio": "Updated content creator and editor",
    "profilePicture": "https://example.com/profile2_new.jpg",
    "socialLinks": {
      "linkedin": "https://linkedin.com/in/iktisad",
      "twitter": "https://twitter.com/iktisad",
      "facebook": "https://facebook.com/iktisad",
      "instagram": "https://instagram.com/iktisad"
    },
    "contactEmail": ["test@test.com", "bestbuy@gmail.com"]
    
  }
}

###------------------------------------###


###-------Get logged in user-----------###
###----->
GET {{api}}/me
Authorization: Bearer {{token}}

###------------------------------------###


###-------------Admin Search-----------###
###----->
GET {{api}}?q=Jane
Authorization: Bearer {{token}}
###---->
GET {{api}}?q=john.doe@example.com
Authorization: Bearer {{token}}

###------------------------------------###


###-------Profile Photo Upload---------###

# POST {{api}}/me/photo
# Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
# Authorization: Bearer {{token}}

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="photo"; filename="D:\icarus\bangla_web_magazine\sample\profile.jpg"
# Content-Type: image/jpeg

# <D:\icarus\bangla_web_magazine\sample\profile.jpg

# ------WebKitFormBoundary7MA4YWxkTrZu0gW--
### Upload User Profile Photo
# POST {{api}}/me/photo
# Content-Type: multipart/form-data boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
# Authorization: Bearer {{token}}

# ----WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="photo"; filename="profile.jpg"
# Content-Type: image/jpeg

# < ../../../sample/profile.jpg
# ----WebKitFormBoundary7MA4YWxkTrZu0gW--

###-----------------------------------###


### request to change password via email
###----Reset Password Request---------###
###----->
POST {{api}}/request-password-reset
Content-Type: application/json

{
  "email": "iktisad.rashid@gmail.com"
}

###-----------------------------------###


### change passward via email link
###-----------Reset Password----------###
###----->
POST {{api}}/reset-password
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlrdGlzYWQucmFzaGlkQGdtYWlsLmNvbSIsImlhdCI6MTcyMzcwNzE1MiwiZXhwIjoxNzIzNzkzNTUyfQ.D8DhaqhP1Eg26l6f43lt0gQun_2nW6b_tdLbMw32D-A",
  "newPassword": "newsecurepass123"
}

###-----------------------------------###


### Change password from profile or account settings
###----->
POST {{api}}/change-password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "currentPassword":"newsecurepass123",
  "newPassword": "securepassword123"
}

###-----------------------------------###