name: Bangla_WEB_Magazine_Backend CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20.11.1"

            - name: Install dependencies
              run: npm install

            - name: Run Unit Tests
              run: npm run test:unit

            - name: Run Integration Tests
              env:
                  MONGOMS_VERSION: 10.0.0
                  MONGOMS_SYSTEM_MEMORY: 2048 # Limit memory usage to 2GB
                  MONGOMS_DOWNLOAD_TIMEOUT: 600000 # Set a long download timeout
                  MONGOMS_SKIP_MD5: true # Skip MD5 validation to save time
                  MONGOMS_PLATFORM: linux # Ensure correct platform is used
                  MONGOMS_ARCH: x64 # Specify architecture
                  MONGOMS_DOWNLOAD_URL: https://your-internal-server.com/mongodb-linux-x86_64-ubuntu2204-5.0.6.tgz
                  MONGOMS_DEBUG: true # Enable debug logs for troubleshooting
              run: npm run test:e2e

        # deploy:
        #   runs-on: ubuntu-latest
        #   needs: build
        #   steps:
        #       - name: Deploy to DigitalOcean
        #         uses: appleboy/ssh-action@v0.1.5
        #         with:
        #             host: ${{ secrets.DROPLET_IP }}
        #             username: ${{ secrets.DROPLET_USER }}
        #             key: ${{ secrets.DROPLET_KEY }}
        #             script: |
        #                 cd /path/to/your/project
        #                 git pull origin main
        #                 npm install
        #                 npm run build
        #                 pm2 restart all
